### ISSUE TITLE
MechComander 2 open fixes

### ISSUE THREAD

**Issue by galorin** [galorin/MechCommander2HD#15]
#4 

Compare 
https://github.com/Echelon9/mechcommander2-open
to codebase, port across any fixes or wanted features.

**Comment by galorin** [comment]
There are significant changes here.  I don't quite know what everything does, but it looks like there are some good memory allocation/deallocation fixes in here.

**Comment by HomelessBill** [comment]
MC2-open is as merged as it's going to get. Lots of little fixes were taken, but that's about it. Memory changes weren't ported across because there are tons and I see no point when we're not having issues with the way they're doing it right now. New features I just left out entirely because it wouldn't compile or run - there's no sense analyzing what might or might not work when we could do it from scratch more easily.
